title: Site

tabs:
  content:
    label: Website
    icon: text
    columns:
      - width: 1/2
        sections:
          information:
            label: Unterseiten
            type: pages
            templates:
              - infohub
              - works
      - width: 1/2
        sections:
          fieldsr:
            type: fields
            fields:
              infoheader:
                label: Kurzinfo
                type: hidden
              description:
                label: Website Meta Beschreibung (SEO)
                type: textarea
